# Created using wingetcreate 0.5.0.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: ArduinoSA.IDE
PackageVersion: 1.8.19
Installers:
- Architecture: x86
  InstallerType: nullsoft
  InstallerUrl: https://downloads.arduino.cc/arduino-1.8.19-windows.exe
  InstallerSha256: 9B480A781E823F81C643A67B1A0E53AD25FCEB1B2A4A90977DF6916877262055
ManifestType: installer
ManifestVersion: 1.1.0

