# Created using wingetcreate 0.5.0.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.1.0.schema.json

PackageIdentifier: Libretro.RetroArch
PackageVersion: 1.10.1.0
Installers:
- Architecture: x64
  InstallerType: nullsoft
  InstallerUrl: https://buildbot.libretro.com/stable/1.10.1/windows/x86_64/RetroArch-Win64-setup.exe
  InstallerSha256: 027B69F363071EB695D52D75C3E7F3778317A01BC1E3EC2033074F591E1756E5
- Architecture: x86
  InstallerType: nullsoft
  InstallerUrl: https://buildbot.libretro.com/stable/1.10.1/windows/x86/RetroArch-Win32-setup.exe
  InstallerSha256: 2B97A640366BA70A093D511BE2430C1F0F84756F7FFAFB1C812EBA2F6EE5B4C4
ManifestType: installer
ManifestVersion: 1.1.0

