# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: MartiCliment.UniGetUI
PackageVersion: 3.2.0
InstallerLocale: en-US
InstallerType: inno
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSuccessCodes:
- 1
UpgradeBehavior: install
ProductCode: '{889610CC-4337-4BDB-AC3B-4F21806C0BDE}_is1'
AppsAndFeaturesEntries:
- DisplayName: UniGetUI
  ProductCode: '{889610CC-4337-4BDB-AC3B-4F21806C0BDE}_is1'
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  Scope: user
  InstallerUrl: https://github.com/marticliment/UniGetUI/releases/download/3.2.0/UniGetUI.Installer.exe
  InstallerSha256: 9674CB060A769236DFA037A4DA485F79B650CCEBEFD5AD1AF5C12E436BDC0A67
  InstallerSwitches:
    Custom: /CURRENTUSER /NoWinGet
- Architecture: x86
  Scope: machine
  InstallerUrl: https://github.com/marticliment/UniGetUI/releases/download/3.2.0/UniGetUI.Installer.exe
  InstallerSha256: 9674CB060A769236DFA037A4DA485F79B650CCEBEFD5AD1AF5C12E436BDC0A67
  InstallerSwitches:
    Custom: /ALLUSERS /NoWinGet
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\UniGetUI'
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2025-05-07
