# Created with komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: OpenJS.NodeJS.LTS
PackageVersion: 22.19.0
Commands:
- corepack
- node
- npm
- npx
FileExtensions:
- cjs
- js
- mjs
ReleaseDate: 2025-08-28
Installers:
- Architecture: x86
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: node-v22.19.0-win-x86/node.exe
  InstallerUrl: https://nodejs.org/dist/v22.19.0/node-v22.19.0-win-x86.zip
  InstallerSha256: 708B8A297A19E9AC433E32AC0FC496755757C5E00BD5A0683917E73CAE5FE8EA
  ArchiveBinariesDependOnPath: true
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: node-v22.19.0-win-x64/node.exe
  InstallerUrl: https://nodejs.org/dist/v22.19.0/node-v22.19.0-win-x64.zip
  InstallerSha256: EA3FAD0E67A991D8477D8C01344B56E69C676CCB733F065B22436994B1253F86
  ArchiveBinariesDependOnPath: true
- Architecture: arm64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: node-v22.19.0-win-arm64/node.exe
  InstallerUrl: https://nodejs.org/dist/v22.19.0/node-v22.19.0-win-arm64.zip
  InstallerSha256: E4A7336010D58FF35B53D9DD5869095C56089C70913CF22508CF8183593E56B2
  ArchiveBinariesDependOnPath: true
- InstallerLocale: en-US
  Architecture: x86
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://nodejs.org/dist/v22.19.0/node-v22.19.0-x86.msi
  InstallerSha256: 96AAE9A1053D3F8C81D04F15D3DB6DEBBBB9DAD418A0B71DCEBAEEB8A5C76AE8
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  UpgradeBehavior: install
  ProductCode: '{7F58DE66-24B1-4D4B-8A08-DC1EBEFD9317}'
  AppsAndFeaturesEntries:
  - DisplayName: Node.js
    ProductCode: '{7F58DE66-24B1-4D4B-8A08-DC1EBEFD9317}'
    UpgradeCode: '{47C07A3A-42EF-4213-A85D-8F5A59077C28}'
  ElevationRequirement: elevatesSelf
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%\nodejs'
- InstallerLocale: en-US
  Architecture: x64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://nodejs.org/dist/v22.19.0/node-v22.19.0-x64.msi
  InstallerSha256: 9D75369D5C62F1D24340C7163CBB252FE29E1950B58095EA5F495998930CCEFA
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  UpgradeBehavior: install
  ProductCode: '{D5D89783-337A-43B7-B476-F14BA3F2FA26}'
  AppsAndFeaturesEntries:
  - DisplayName: Node.js
    ProductCode: '{D5D89783-337A-43B7-B476-F14BA3F2FA26}'
    UpgradeCode: '{47C07A3A-42EF-4213-A85D-8F5A59077C28}'
  ElevationRequirement: elevatesSelf
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\nodejs'
- InstallerLocale: en-US
  Architecture: arm64
  InstallerType: wix
  Scope: machine
  InstallerUrl: https://nodejs.org/dist/v22.19.0/node-v22.19.0-arm64.msi
  InstallerSha256: 0B9EACC6CA3833FBCCDB7636BD668BACDBB88FE404A980EFA50014B84E42953C
  InstallerSwitches:
    InstallLocation: INSTALLDIR="<INSTALLPATH>"
  UpgradeBehavior: install
  ProductCode: '{E3944B4F-0CA4-43FD-B74A-F7E502F9275B}'
  AppsAndFeaturesEntries:
  - DisplayName: Node.js
    ProductCode: '{E3944B4F-0CA4-43FD-B74A-F7E502F9275B}'
    UpgradeCode: '{47C07A3A-42EF-4213-A85D-8F5A59077C28}'
  ElevationRequirement: elevatesSelf
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\nodejs'
ManifestType: installer
ManifestVersion: 1.10.0
