# Created with WinGet Releaser using komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: mq1.TinyWiiBackupManager
PackageVersion: 4.2.0
PackageLocale: en-US
Publisher: mq1
PublisherUrl: https://github.com/mq1
PublisherSupportUrl: https://github.com/mq1/TinyWiiBackupManager/issues
Author: Manuel Quarneti <mq1@ik.me>
PackageName: TinyWiiBackupManager
PackageUrl: https://github.com/mq1/TinyWiiBackupManager
License: GPL-3.0
LicenseUrl: https://github.com/mq1/TinyWiiBackupManager/blob/main/COPYING
Copyright: Copyright (c) 2025 Manuel Quarneti
ShortDescription: A dead simple Wii backup manager.
Moniker: wii-backup-manager
Tags:
- backup
- game-manager
- gamecube
- homebrew
- wbfs
- wii
ReleaseNotes: |-
  What's Changed
  - ✨ Add tools view by @mq1 in #264
  - ✨ Add cheat downloading by @mq1 in #265
  - ✨ Add banner downloading (GameCube) by @mq1 in #266
  - ✨ Add proper WiiFlow Lite cover downloading by @mq1 in #267
  - 🚸 Show full drive path on title bar by @mq1 in #268
  - ✨ Add TWBM info dialog by @mq1 in #269
  - 🐛 Fix covers not refreshing after downloading by @mq1 in #271
  - 🚸 Improve skipping existing games by @mq1 in #272
  - 🚸 Change "Remove" text to "Delete" by @mq1 in #273
  - ⬆️ Update rust to 1.91.0 by @mq1 in #274
  - 🚸 Look for games recursively by @mq1 in #275
  - Revert "🚸 Look for games recursively" by @mq1 in #276
  - ✨ Show a conversion transaction overview before starting it by @mq1 in #277
  - 🚸 Separate Wii/GC games by @mq1 in #278
  - 💄 Make the fallback accent color orange (rust-like) by @mq1 in #280
  Full Changelog: 4.1.3...4.2.0
  ⬇️ Download for Windows 10+ ^{(pick the first if unsure)}
  - Standalone (x64) Standalone (arm64) Standalone (x86)
  - Installer (x64)
  - Portable (x64) Portable (arm64) Portable (x86)
  ⬇️ Download for Linux
  - AppImage (x86_64) AppImage (aarch64)
  - tar.gz (x86_64) tar.gz (aarch64) tar.gz (i686)
  ⬇️ Download for macOS
  - dmg (Apple Silicon) dmg (Intel)
  > ⚠️ macOS installation
  > The app is not notarized, you must allow it manually after installing by running this command in Terminal:
  >
  > xattr -rd com.apple.quarantine /Applications/TinyWiiBackupManager.app
  ⬇️ Download for Windows 7 / 8 / 8.1 ^{(untested and unsupported)}
  - Standalone (x64) Standalone (x86)
  - Portable (x64) Portable (x86)
ReleaseNotesUrl: https://github.com/mq1/TinyWiiBackupManager/releases/tag/4.2.0
Documentations:
- DocumentLabel: Wiki
  DocumentUrl: https://github.com/mq1/TinyWiiBackupManager/wiki
ManifestType: defaultLocale
ManifestVersion: 1.10.0
