# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: QuestPackageManager.QuestPackageManager
PackageVersion: 1.4.2
InstallerType: inno
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/DanTheMan827/QPM.CLI/releases/download/v1.4.2/qpm-installer.exe
  InstallerSha256: 65E529ED0ADA7B6BE2AB75C6D3B65DD09CBB9400AA5AD0B1CE31BDD2A367C3C8
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2025-02-14
