# Created using wingetcreate 1.9.4.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.9.0.schema.json

PackageIdentifier: nirsoft.nircmd
PackageVersion: "2.87"
PackageLocale: en-US
Publisher: NirSoft
PackageName: NirCmd
License: Freeware
ShortDescription: NirCmd is a small command-line utility that allows you to do some useful tasks without displaying any user interface.
ManifestType: defaultLocale
ManifestVersion: 1.9.0
