# Created with WinGet Releaser using komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: PRQL.prqlc
PackageVersion: 0.13.6
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: prqlc.exe
Scope: user
UpgradeBehavior: install
ReleaseDate: 2025-11-01
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/PRQL/prql/releases/download/0.13.6/prqlc-0.13.6-x86_64-pc-windows-msvc.zip
  InstallerSha256: 00F6377D057991A4033EDE1C600363A2EF02013337CC6AA6F86AC669F5595656
ManifestType: installer
ManifestVersion: 1.10.0
