# Created using wingetcreate 0.5.0.1
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.1.0.schema.json

PackageIdentifier: Google.Picasa
PackageVersion: 3.9.141.259
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.1.0

