name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN || secrets.GITHUB_TOKEN }}
          ref: master

      - name: Add Upstream and Fetch
        run: |
          git remote add upstream https://github.com/microsoft/winget-pkgs.git
          git fetch upstream

      - name: Reset to Upstream
        run: |
          git checkout master
          git reset --hard upstream/master

      - name: Push changes to fork
        run: |
          git push origin master --force
